### ISSUE TITLE
Support sbt

### ISSUE THREAD

**Issue by relekang** [frigg/vagrant-frigg-worker#4]

**Comment by relekang** [comment]
```yaml
sbt-ppa:
  pkgrepo.managed:
    - humanname: SBT
    - name: deb http://dl.bintray.com/sbt/debian /
    - file: /etc/apt/sources.list.d/sbt.list

sbt:
  pkg:
  - installed
  - require:
      - pkgrepo: sbt-ppa
```

gives the error: `E: There are problems and -y was used without --force-yes`
